---

- name: Overwrite default init properties
  lineinfile:
    path: "{{ jenkins_init_file }}"
    regexp: "^{{ item.property }}"
    line: "{{ item.property }}={{ item.value }}"
  with_items: "{{ jenkins_init_properties }}"

- name: Extend default init properties
  lineinfile:
    path: "{{ jenkins_init_file }}"
    insertafter: '^{{ item.property }}='
    regexp: '^{{ item.property }}=\"\${{ item.property }} '
    line: '{{ item.property }}="${{ item.property }} {{ item.value }}"'
    state: present
  with_items:
    "{{ jenkins_init_properties_extended }}"
